class DbQueryStorage {
    getLogByDateQuery = 
    `     WITH START_BAT AS (
         SELECT ROW_NUMBER() OVER (PARTITION BY S.PROCESS_NAME ORDER BY S.TIME ) AS ROW_NUM, S.PROCESS_NAME,
             S.TIME AS START_TIME
         FROM PROCCESS_SUMMARIZED_DATALOGS S
         WHERE DATE(S.TIME) = DATE(?) 
         AND S.MESSAGE IN ('START_BATCH')
     ), END_BAT AS (
         SELECT ROW_NUMBER() OVER (PARTITION BY E.PROCESS_NAME ORDER BY E.TIME ) AS ROW_NUM, E.PROCESS_NAME,
             E.TIME AS END_TIME,
             E.ERROR_MESSAGE AS ERROR_MESSAGE
         FROM PROCCESS_SUMMARIZED_DATALOGS E
         WHERE DATE(E.TIME) = DATE(?) 
         AND E.MESSAGE IN ('END_BATCH')
     )
     SELECT S.ROW_NUM, 
         COALESCE(S.PROCESS_NAME, E.PROCESS_NAME) AS PROCESS_NAME,
         S.START_TIME,
         E.END_TIME,
         TIME(STRFTIME('%s', E.END_TIME) - STRFTIME('%s', S.START_TIME), 'unixepoch') AS DURATION,
         CASE WHEN UPPER(E.ERROR_MESSAGE) = 'ERROR' THEN 'FAILED' ELSE 'SUCCESS' END AS STATUS
     FROM START_BAT S 
     FULL OUTER JOIN END_BAT E
     ON S.ROW_NUM = E.ROW_NUM AND S.PROCESS_NAME = E.PROCESS_NAME
     ORDER BY  COALESCE(S.PROCESS_NAME, E.PROCESS_NAME), S.ROW_NUM`;

     insertBatchLog = 
     `
    INSERT INTO PROCCESS_SUMMARIZED_DATALOGS(TIME, PROCESS_NAME, MESSAGE, ERROR_MESSAGE) 
    VALUES (@time, @processName, @message, @errorMessage)
     `

}

export default DbQueryStorage;